// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"eratani_assesment_test/TestCase_3/configs"
	"eratani_assesment_test/TestCase_3/database"
	"eratani_assesment_test/TestCase_3/internal/domain/credit_card/repository"
	"eratani_assesment_test/TestCase_3/internal/domain/credit_card/service"
	"eratani_assesment_test/TestCase_3/internal/handler/credit_card"
	"eratani_assesment_test/TestCase_3/transport/http"
	"eratani_assesment_test/TestCase_3/transport/http/router"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeHTTPService initializes the HTTP service with all dependencies
func InitializeHTTPService() *http.HTTP {
	config := configs.Get()
	postgresConn := database.ProvidePostgresConn(config)
	creditCardRepositoryPostgres := repository.ProvideUserRepository(postgresConn)
	creditCardServiceImpl := service.ProvideUserService(creditCardRepositoryPostgres)
	creditCardHandler := handler.ProvideUserHandler(creditCardServiceImpl)
	domainHandlers := router.DomainHandlers{
		CreditCardHandler: creditCardHandler,
	}
	routerRouter := router.ProvideRouter(domainHandlers)
	httpHTTP := http.ProvideHTTP(config, postgresConn, routerRouter)
	return httpHTTP
}

// wire.go:

// Config provider
var configGen = wire.NewSet(configs.Get)

// Database provider
var databaseGen = wire.NewSet(database.ProvidePostgresConn)

// Repository provider + binding
var repoGen = wire.NewSet(repository.ProvideUserRepository, wire.Bind(new(repository.CreditCardRepository), new(*repository.CreditCardRepositoryPostgres)))

// Service provider + binding
var svcGen = wire.NewSet(service.ProvideUserService, wire.Bind(new(service.CreditCardService), new(*service.CreditCardServiceImpl)))

// Handler provider
var handlerGen = wire.NewSet(handler.ProvideUserHandler)

// Domain handlers provider
var domainHandlersGen = wire.NewSet(wire.Struct(new(router.DomainHandlers), "*"))

// Router provider
var routerGen = wire.NewSet(router.ProvideRouter)

// HTTP provider
var httpGen = wire.NewSet(http.ProvideHTTP)
